@extends('layouts.site')
@section('title', ($post->exists ? 'Edit post' : 'Write a post').' — blogshed.uk')
@section('content')<section class="wrap admin-area">@include('admin.navigation')<a class="text-link" href="{{ route('admin.posts.index') }}">← All posts</a><h1>{{ $post->exists ? 'Make it your own.' : 'A new field note.' }}</h1>
@if($errors->any())<div class="error-box" role="alert"><strong>Please check the following:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form class="editor-form" method="POST" enctype="multipart/form-data" action="{{ $post->exists ? route('admin.posts.update', $post) : route('admin.posts.store') }}">@csrf @if($post->exists) @method('PUT') @endif
<div class="panel"><label for="title">Post title</label><input id="title" name="title" value="{{ old('title', $post->title) }}" required maxlength="255" placeholder="Give your story a title"><label for="seo_summary">Short description</label><textarea id="seo_summary" name="seo_summary" rows="3" required maxlength="255">{{ old('seo_summary', $post->seo_summary) }}</textarea><p class="field-help">A brief introduction for the blog cards and search engines. Up to 255 characters.</p>
<label for="body">Your story</label><textarea id="body" name="body" rows="20" data-editor>{{ old('body', $post->body) }}</textarea><p class="field-help" id="editor-status" role="status">Loading your writing tools…</p>
@if($post->exists)<details class="draft-preview"><summary>Preview saved content</summary><div class="prose">{!! $post->body !!}</div></details>@endif</div>
<aside><div class="panel"><h3>Publish your post</h3><label for="post_date">Publication date</label><input id="post_date" type="date" name="post_date" value="{{ old('post_date', $post->post_date?->format('Y-m-d') ?? today()->format('Y-m-d')) }}" required><p class="field-help">A future date keeps a published post hidden until that day.</p><button class="button full" name="action" value="publish">{{ $post->exists ? 'Save & publish' : 'Publish post' }} ↗</button><button class="button secondary full" name="action" value="draft">Save as draft</button></div><div class="panel"><h3>Cover image</h3>@if($post->image)<img class="admin-thumbnail" src="{{ app(\App\Services\BlogImages::class)->url($post->image, 'thumbnail') }}" alt="Current cover"><label class="check-label"><input type="checkbox" name="remove_image" value="1" @checked(old('remove_image'))> Remove current image</label>@endif<label for="image">{{ $post->image ? 'Replace image' : 'Choose an image' }}</label><input id="image" type="file" name="image" accept="image/jpeg,image/png,image/webp"><p class="field-help">JPG, PNG or WebP. Up to 8 MB and 6,000 pixels per side. Automatically resized to 400, 800 and 1,600 pixels and compressed to WebP.</p><label for="image_alt">Image description</label><input id="image_alt" name="image_alt" value="{{ old('image_alt', $post->image_alt) }}" maxlength="255"><p class="field-help">Describe the image for people using screen readers.</p></div></aside></form></section>
@endsection